### ISSUE TITLE
Rename package

### ISSUE THREAD

**Issue by BrainRTP** [MRGRD56/mgutils#5]
I couldn't find a naming convention for "problem" packages, using numbers as an example, but I was able to dig up this article - https://habr.com/ru/articles/755654/#4. 

From the example in the article:
> hyphenated-name.example.org → org.example.hyphenated_name
example.int → int_.example
123name.example.com → com.example._123name

I suggest renaming to:
`com._37bytes.dev.libs`
or
`io._37b.dev.libs.`

Or abandon dev.libs altogether

First, keep the reverse domain.
Second, it reads better than dev.b37.libs _(what's a b37? reversed name is bad :-( )_

**Comment by MRGRD56** [comment]
look at this package https://github.com/37bytes/browser-support/blob/master/pom.xml

```xml
<groupId>dev.b37.libs</groupId>
<artifactId>browser-support</artifactId>
```

we have `dev.b37.libs` here too  
I decided to use it here as well

> what's a b37?

we do have `b37.dev` domain registered! (you can open it in browser)

so I think it's okay to use this domain as the package name 🤔

**Comment by BrainRTP** [comment]
> we do have b37.dev domain registered! (you can open it in browser)

damn, by bad :-) 

Thx
